<?php

return [
    'countries' => [
        "AFG" => ["country" => "Afghanistan", "continent" => "Asia"],
        "ALA" => ["country" => "Åland Islands", "continent" => "Europe"],
        "ALB" => ["country" => "Albania", "continent" => "Europe"],
        "DZA" => ["country" => "Algeria", "continent" => "Africa"],
        "ASM" => ["country" => "American Samoa", "continent" => "Oceania"],
        "AND" => ["country" => "Andorra", "continent" => "Europe"],
        "AGO" => ["country" => "Angola", "continent" => "Africa"],
        "AIA" => ["country" => "Anguilla", "continent" => "North America"],
        "ATA" => ["country" => "Antarctica", "continent" => "Antarctica"],
        "ATG" => ["country" => "Antigua and Barbuda", "continent" => "North America"],
        "ARG" => ["country" => "Argentina", "continent" => "South America"],
        "ARM" => ["country" => "Armenia", "continent" => "Asia"],
        "ABW" => ["country" => "Aruba", "continent" => "North America"],
        "AUS" => ["country" => "Australia", "continent" => "Oceania"],
        "AUT" => ["country" => "Austria", "continent" => "Europe"],
        "AZE" => ["country" => "Azerbaijan", "continent" => "Asia"],
        "BHS" => ["country" => "Bahamas", "continent" => "North America"],
        "BHR" => ["country" => "Bahrain", "continent" => "Asia"],
        "BGD" => ["country" => "Bangladesh", "continent" => "Asia"],
        "BRB" => ["country" => "Barbados", "continent" => "North America"],
        "BLR" => ["country" => "Belarus", "continent" => "Europe"],
        "BEL" => ["country" => "Belgium", "continent" => "Europe"],
        "BLZ" => ["country" => "Belize", "continent" => "North America"],
        "BEN" => ["country" => "Benin", "continent" => "Africa"],
        "BMU" => ["country" => "Bermuda", "continent" => "North America"],
        "BTN" => ["country" => "Bhutan", "continent" => "Asia"],
        "BOL" => ["country" => "Bolivia", "continent" => "South America"],
        "BIH" => ["country" => "Bosnia and Herzegovina", "continent" => "Europe"],
        "BWA" => ["country" => "Botswana", "continent" => "Africa"],
        "BVT" => ["country" => "Bouvet Island", "continent" => "Antarctica"],
        "BRA" => ["country" => "Brazil", "continent" => "South America"],
        "IOT" => ["country" => "British Indian Ocean Territory", "continent" => "Asia"],
        "BRN" => ["country" => "Brunei Darussalam", "continent" => "Asia"],
        "BGR" => ["country" => "Bulgaria", "continent" => "Europe"],
        "BFA" => ["country" => "Burkina Faso", "continent" => "Africa"],
        "BDI" => ["country" => "Burundi", "continent" => "Africa"],
        "KHM" => ["country" => "Cambodia", "continent" => "Asia"],
        "CMR" => ["country" => "Cameroon", "continent" => "Africa"],
        "CAN" => ["country" => "Canada", "continent" => "North America"],
        "CPV" => ["country" => "Cape Verde", "continent" => "Africa"],
        "CYM" => ["country" => "Cayman Islands", "continent" => "North America"],
        "CAF" => ["country" => "Central African Republic", "continent" => "Africa"],
        "TCD" => ["country" => "Chad", "continent" => "Africa"],
        "CHL" => ["country" => "Chile", "continent" => "South America"],
        "CHN" => ["country" => "China", "continent" => "Asia"],
        "CXR" => ["country" => "Christmas Island", "continent" => "Asia"],
        "CCK" => ["country" => "Cocos (Keeling) Islands", "continent" => "Asia"],
        "COL" => ["country" => "Colombia", "continent" => "South America"],
        "COM" => ["country" => "Comoros", "continent" => "Africa"],
        "COG" => ["country" => "Congo", "continent" => "Africa"],
        "COD" => ["country" => "The Democratic Republic of The Congo", "continent" => "Africa"],
        "COK" => ["country" => "Cook Islands", "continent" => "Oceania"],
        "CRI" => ["country" => "Costa Rica", "continent" => "North America"],
        "CIV" => ["country" => "Cote D'ivoire", "continent" => "Africa"],
        "HRV" => ["country" => "Croatia", "continent" => "Europe"],
        "CUB" => ["country" => "Cuba", "continent" => "North America"],
        "CYP" => ["country" => "Cyprus", "continent" => "Asia"],
        "CZE" => ["country" => "Czech Republic", "continent" => "Europe"],
        "DNK" => ["country" => "Denmark", "continent" => "Europe"],
        "DJI" => ["country" => "Djibouti", "continent" => "Africa"],
        "DMA" => ["country" => "Dominica", "continent" => "North America"],
        "DOM" => ["country" => "Dominican Republic", "continent" => "North America"],
        "ECU" => ["country" => "Ecuador", "continent" => "South America"],
        "EGY" => ["country" => "Egypt", "continent" => "Africa"],
        "SLV" => ["country" => "El Salvador", "continent" => "North America"],
        "GNQ" => ["country" => "Equatorial Guinea", "continent" => "Africa"],
        "ERI" => ["country" => "Eritrea", "continent" => "Africa"],
        "EST" => ["country" => "Estonia", "continent" => "Europe"],
        "ETH" => ["country" => "Ethiopia", "continent" => "Africa"],
        "FLK" => ["country" => "Falkland Islands (Malvinas)", "continent" => "South America"],
        "FRO" => ["country" => "Faroe Islands", "continent" => "Europe"],
        "FJI" => ["country" => "Fiji", "continent" => "Oceania"],
        "FIN" => ["country" => "Finland", "continent" => "Europe"],
        "FRA" => ["country" => "France", "continent" => "Europe"],
        "GUF" => ["country" => "French Guiana", "continent" => "South America"],
        "PYF" => ["country" => "French Polynesia", "continent" => "Oceania"],
        "ATF" => ["country" => "French Southern Territories", "continent" => "Antarctica"],
        "GAB" => ["country" => "Gabon", "continent" => "Africa"],
        "GMB" => ["country" => "Gambia", "continent" => "Africa"],
        "GEO" => ["country" => "Georgia", "continent" => "Asia"],
        "DEU" => ["country" => "Germany", "continent" => "Europe"],
        "GHA" => ["country" => "Ghana", "continent" => "Africa"],
        "GIB" => ["country" => "Gibraltar", "continent" => "Europe"],
        "GRC" => ["country" => "Greece", "continent" => "Europe"],
        "GRL" => ["country" => "Greenland", "continent" => "North America"],
        "GRD" => ["country" => "Grenada", "continent" => "North America"],
        "GLP" => ["country" => "Guadeloupe", "continent" => "North America"],
        "GUM" => ["country" => "Guam", "continent" => "Oceania"],
        "GTM" => ["country" => "Guatemala", "continent" => "North America"],
        "GGY" => ["country" => "Guernsey", "continent" => "Europe"],
        "GIN" => ["country" => "Guinea", "continent" => "Africa"],
        "GNB" => ["country" => "Guinea-bissau", "continent" => "Africa"],
        "GUY" => ["country" => "Guyana", "continent" => "South America"],
        "HTI" => ["country" => "Haiti", "continent" => "North America"],
        "HMD" => ["country" => "Heard Island and Mcdonald Islands", "continent" => "Antarctica"],
        "VAT" => ["country" => "Holy See (Vatican City State)", "continent" => "Europe"],
        "HND" => ["country" => "Honduras", "continent" => "North America"],
        "HKG" => ["country" => "Hong Kong", "continent" => "Asia"],
        "HUN" => ["country" => "Hungary", "continent" => "Europe"],
        "ISL" => ["country" => "Iceland", "continent" => "Europe"],
        "IND" => ["country" => "India", "continent" => "Asia"],
        "IDN" => ["country" => "Indonesia", "continent" => "Asia"],
        "IRN" => ["country" => "Iran", "continent" => "Asia"],
        "IRQ" => ["country" => "Iraq", "continent" => "Asia"],
        "IRL" => ["country" => "Ireland", "continent" => "Europe"],
        "IMN" => ["country" => "Isle of Man", "continent" => "Europe"],
        "ISR" => ["country" => "Israel", "continent" => "Asia"],
        "ITA" => ["country" => "Italy", "continent" => "Europe"],
        "JAM" => ["country" => "Jamaica", "continent" => "North America"],
        "JPN" => ["country" => "Japan", "continent" => "Asia"],
        "JEY" => ["country" => "Jersey", "continent" => "Europe"],
        "JOR" => ["country" => "Jordan", "continent" => "Asia"],
        "KAZ" => ["country" => "Kazakhstan", "continent" => "Asia"],
        "KEN" => ["country" => "Kenya", "continent" => "Africa"],
        "KIR" => ["country" => "Kiribati", "continent" => "Oceania"],
        "PRK" => ["country" => "Democratic People's Republic of Korea", "continent" => "Asia"],
        "KOR" => ["country" => "Republic of Korea", "continent" => "Asia"],
        "KWT" => ["country" => "Kuwait", "continent" => "Asia"],
        "KGZ" => ["country" => "Kyrgyzstan", "continent" => "Asia"],
        "LAO" => ["country" => "Lao People's Democratic Republic", "continent" => "Asia"],
        "LVA" => ["country" => "Latvia", "continent" => "Europe"],
        "LBN" => ["country" => "Lebanon", "continent" => "Asia"],
        "LSO" => ["country" => "Lesotho", "continent" => "Africa"],
        "LBR" => ["country" => "Liberia", "continent" => "Africa"],
        "LBY" => ["country" => "Libya", "continent" => "Africa"],
        "LIE" => ["country" => "Liechtenstein", "continent" => "Europe"],
        "LTU" => ["country" => "Lithuania", "continent" => "Europe"],
        "LUX" => ["country" => "Luxembourg", "continent" => "Europe"],
        "MAC" => ["country" => "Macao", "continent" => "Asia"],
        "MKD" => ["country" => "Macedonia", "continent" => "Europe"],
        "MDG" => ["country" => "Madagascar", "continent" => "Africa"],
        "MWI" => ["country" => "Malawi", "continent" => "Africa"],
        "MYS" => ["country" => "Malaysia", "continent" => "Asia"],
        "MDV" => ["country" => "Maldives", "continent" => "Asia"],
        "MLI" => ["country" => "Mali", "continent" => "Africa"],
        "MLT" => ["country" => "Malta", "continent" => "Europe"],
        "MHL" => ["country" => "Marshall Islands", "continent" => "Oceania"],
        "MTQ" => ["country" => "Martinique", "continent" => "North America"],
        "MRT" => ["country" => "Mauritania", "continent" => "Africa"],
        "MUS" => ["country" => "Mauritius", "continent" => "Africa"],
        "MYT" => ["country" => "Mayotte", "continent" => "Africa"],
        "MEX" => ["country" => "Mexico", "continent" => "North America"],
        "FSM" => ["country" => "Micronesia", "continent" => "Oceania"],
        "MDA" => ["country" => "Moldova", "continent" => "Europe"],
        "MCO" => ["country" => "Monaco", "continent" => "Europe"],
        "MNG" => ["country" => "Mongolia", "continent" => "Asia"],
        "MNE" => ["country" => "Montenegro", "continent" => "Europe"],
        "MSR" => ["country" => "Montserrat", "continent" => "North America"],
        "MAR" => ["country" => "Morocco", "continent" => "Africa"],
        "MOZ" => ["country" => "Mozambique", "continent" => "Africa"],
        "MMR" => ["country" => "Myanmar", "continent" => "Asia"],
        "NAM" => ["country" => "Namibia", "continent" => "Africa"],
        "NRU" => ["country" => "Nauru", "continent" => "Oceania"],
        "NPL" => ["country" => "Nepal", "continent" => "Asia"],
        "NLD" => ["country" => "Netherlands", "continent" => "Europe"],
        "ANT" => ["country" => "Netherlands Antilles", "continent" => "North America"],
        "NCL" => ["country" => "New Caledonia", "continent" => "Oceania"],
        "NZL" => ["country" => "New Zealand", "continent" => "Oceania"],
        "NIC" => ["country" => "Nicaragua", "continent" => "North America"],
        "NER" => ["country" => "Niger", "continent" => "Africa"],
        "NGA" => ["country" => "Nigeria", "continent" => "Africa"],
        "NIU" => ["country" => "Niue", "continent" => "Oceania"],
        "NFK" => ["country" => "Norfolk Island", "continent" => "Oceania"],
        "MNP" => ["country" => "Northern Mariana Islands", "continent" => "Oceania"],
        "NOR" => ["country" => "Norway", "continent" => "Europe"],
        "OMN" => ["country" => "Oman", "continent" => "Asia"],
        "PAK" => ["country" => "Pakistan", "continent" => "Asia"],
        "PLW" => ["country" => "Palau", "continent" => "Oceania"],
        "PSE" => ["country" => "Palestinia", "continent" => "Asia"],
        "PAN" => ["country" => "Panama", "continent" => "North America"],
        "PNG" => ["country" => "Papua New Guinea", "continent" => "Oceania"],
        "PRY" => ["country" => "Paraguay", "continent" => "South America"],
        "PER" => ["country" => "Peru", "continent" => "South America"],
        "PHL" => ["country" => "Philippines", "continent" => "Asia"],
        "PCN" => ["country" => "Pitcairn", "continent" => "Oceania"],
        "POL" => ["country" => "Poland", "continent" => "Europe"],
        "PRT" => ["country" => "Portugal", "continent" => "Europe"],
        "PRI" => ["country" => "Puerto Rico", "continent" => "North America"],
        "QAT" => ["country" => "Qatar", "continent" => "Asia"],
        "REU" => ["country" => "Reunion", "continent" => "Africa"],
        "ROU" => ["country" => "Romania", "continent" => "Europe"],
        "RUS" => ["country" => "Russian Federation", "continent" => "Europe"],
        "RWA" => ["country" => "Rwanda", "continent" => "Africa"],
        "SHN" => ["country" => "Saint Helena", "continent" => "Africa"],
        "KNA" => ["country" => "Saint Kitts and Nevis", "continent" => "North America"],
        "LCA" => ["country" => "Saint Lucia", "continent" => "North America"],
        "SPM" => ["country" => "Saint Pierre and Miquelon", "continent" => "North America"],
        "VCT" => ["country" => "Saint Vincent and The Grenadines", "continent" => "North America"],
        "WSM" => ["country" => "Samoa", "continent" => "Oceania"],
        "SMR" => ["country" => "San Marino", "continent" => "Europe"],
        "STP" => ["country" => "Sao Tome and Principe", "continent" => "Africa"],
        "SAU" => ["country" => "Saudi Arabia", "continent" => "Asia"],
        "SEN" => ["country" => "Senegal", "continent" => "Africa"],
        "SRB" => ["country" => "Serbia", "continent" => "Europe"],
        "SYC" => ["country" => "Seychelles", "continent" => "Africa"],
        "SLE" => ["country" => "Sierra Leone", "continent" => "Africa"],
        "SGP" => ["country" => "Singapore", "continent" => "Asia"],
        "SVK" => ["country" => "Slovakia", "continent" => "Europe"],
        "SVN" => ["country" => "Slovenia", "continent" => "Europe"],
        "SLB" => ["country" => "Solomon Islands", "continent" => "Oceania"],
        "SOM" => ["country" => "Somalia", "continent" => "Africa"],
        "ZAF" => ["country" => "South Africa", "continent" => "Africa"],
        "SGS" => ["country" => "South Georgia and The South Sandwich Islands", "continent" => "Antarctica"],
        "SSD" => ["country" => "South Sudan", "continent" => "Africa"],
        "ESP" => ["country" => "Spain", "continent" => "Europe"],
        "LKA" => ["country" => "Sri Lanka", "continent" => "Asia"],
        "SDN" => ["country" => "Sudan", "continent" => "Africa"],
        "SUR" => ["country" => "Suriname", "continent" => "South America"],
        "SJM" => ["country" => "Svalbard and Jan Mayen", "continent" => "Europe"],
        "SWZ" => ["country" => "Swaziland", "continent" => "Africa"],
        "SWE" => ["country" => "Sweden", "continent" => "Europe"],
        "CHE" => ["country" => "Switzerland", "continent" => "Europe"],
        "SYR" => ["country" => "Syrian Arab Republic", "continent" => "Asia"],
        "TWN" => ["country" => "Taiwan, Province of China", "continent" => "Asia"],
        "TJK" => ["country" => "Tajikistan", "continent" => "Asia"],
        "TZA" => ["country" => "Tanzania, United Republic of", "continent" => "Africa"],
        "THA" => ["country" => "Thailand", "continent" => "Asia"],
        "TLS" => ["country" => "Timor-leste", "continent" => "Asia"],
        "TGO" => ["country" => "Togo", "continent" => "Africa"],
        "TKL" => ["country" => "Tokelau", "continent" => "Oceania"],
        "TON" => ["country" => "Tonga", "continent" => "Oceania"],
        "TTO" => ["country" => "Trinidad and Tobago", "continent" => "North America"],
        "TUN" => ["country" => "Tunisia", "continent" => "Africa"],
        "TUR" => ["country" => "Turkey", "continent" => "Asia"],
        "TKM" => ["country" => "Turkmenistan", "continent" => "Asia"],
        "TCA" => ["country" => "Turks and Caicos Islands", "continent" => "North America"],
        "TUV" => ["country" => "Tuvalu", "continent" => "Oceania"],
        "UGA" => ["country" => "Uganda", "continent" => "Africa"],
        "UKR" => ["country" => "Ukraine", "continent" => "Europe"],
        "ARE" => ["country" => "United Arab Emirates", "continent" => "Asia"],
        "GBR" => ["country" => "United Kingdom", "continent" => "Europe"],
        "USA" => ["country" => "United States", "continent" => "North America"],
        "UMI" => ["country" => "United States Minor Outlying Islands", "continent" => "Oceania"],
        "URY" => ["country" => "Uruguay", "continent" => "South America"],
        "UZB" => ["country" => "Uzbekistan", "continent" => "Asia"],
        "VUT" => ["country" => "Vanuatu", "continent" => "Oceania"],
        "VEN" => ["country" => "Venezuela", "continent" => "South America"],
        "VNM" => ["country" => "Viet Nam", "continent" => "Asia"],
        "VGB" => ["country" => "Virgin Islands, British", "continent" => "North America"],
        "VIR" => ["country" => "Virgin Islands, U.S.", "continent" => "North America"],
        "WLF" => ["country" => "Wallis and Futuna", "continent" => "Oceania"],
        "ESH" => ["country" => "Western Sahara", "continent" => "Africa"],
        "YEM" => ["country" => "Yemen", "continent" => "Asia"],
        "ZMB" => ["country" => "Zambia", "continent" => "Africa"],
        "ZWE" => ["country" => "Zimbabwe", "continent" => "Africa"]
    ],

    'states' => [
        0 => [
            'name' => 'Abia',
            'capital' => 'Umuahia',
            'lga' => [
                'Aba North',
                'Aba South',
                'Arochukwu',
                'Bende',
                'Ikwano',
                'Isiala Ngwa North',
                'Isiala Ngwa South',
                'Isuikwuato',
                'Obingwa',
                'Ohafia',
                'Osisioma',
                'Ugwunagbo',
                'Ukwa East',
                'Ukwa West',
                'Umuahia North',
                'Umuahia South',
                'Umuneochi',
            ]
        ],
        1 => [
            'name' => 'Adamawa',
            'capital' => 'Yola',
            'lga' => [
                'Demsa',
                'Fufore',
                'Ganaye',
                'Gireri',
                'Gombi',
                'Guyuk',
                'Hong',
                'Jada',
                'Lamurde',
                'Madagali',
                'Maiha',
                'Mayo-Belwa',
                'Michika',
                'Mubi North',
                'Mubi South',
                'Numan',
                'Shelleng',
                'Song',
                'Toungo',
                'Yola North',
                'Yola South',
            ]
        ],
        2 => [
            'name' => 'Akwa Ibom',
            'capital' => 'Uyo',
            'lga' => [
                'Abak',
                'Eastern Obolo',
                'Eket',
                'Esit Eket',
                'Essien Udim',
                'Etim Ekpo',
                'Etinan',
                'Ibeno',
                'Ibesikpo Asutan',
                'Ibiono Ibom',
                'Ika',
                'Ikono',
                'Ikot Abasi',
                'Ikot Ekpene',
                'Ini',
                'Itu',
                'Mbo',
                'Mkpat Enin',
                'Nsit Atai',
                'Nsit Ibom',
                'Nsit Ubium',
                'Obot Akara',
                'Okobo',
                'Onna',
                'Oron',
                'Oruk Anam',
                'Udung Uko',
                'Ukanafun',
                'Uruan',
                'Urue-Offong/Oruko',
                'Uyo',
            ]
        ],
        3 => [
            'name' => 'Anambra',
            'capital' => 'Awka',
            'lga' => [
                'Aguata',
                'Anambra East',
                'Anambra West',
                'Anaocha',
                'Awka North',
                'Awka South',
                'Ayamelum',
                'Dunukofia',
                'Ekwusigo',
                'Idemili North',
                'Idemili south',
                'Ihiala',
                'Njikoka',
                'Nnewi North',
                'Nnewi South',
                'Ogbaru',
                'Onitsha North',
                'Onitsha South',
                'Orumba North',
                'Orumba South',
                'Oyi',
            ]
        ],
        4 => [
            'name' => 'Bauchi',
            'capital' => 'Bauchi',
            'lga' => [
                'Alkaleri',
                'Bauchi',
                'Bogoro',
                'Damban',
                'Darazo',
                'Dass',
                'Ganjuwa',
                'Giade',
                'Itas/Gadau',
                'Jama\'are',
                'Katagum',
                'Kirfi',
                'Misau',
                'Ningi',
                'Shira',
                'Tafawa-Balewa',
                'Toro',
                'Warji',
                'Zaki'
            ]
        ],
        5 => [
            'name' => 'Bayelsa',
            'capital' => 'Yenagoa',
            'lga' => [
                'Brass',
                'Ekeremor',
                'Kolokuma/Opokuma',
                'Nembe',
                'Ogbia',
                'Sagbama',
                'Southern Jaw',
                'Yenegoa'
            ]
        ],
        6 => [
            'name' => 'Benue',
            'capital' => 'Makurdi',
            'lga' => [
                'Ado',
                'Agatu',
                'Apa',
                'Buruku',
                'Gboko',
                'Guma',
                'Gwer East',
                'Gwer West',
                'Katsina-Ala',
                'Konshisha',
                'Kwande',
                'Logo',
                'Makurdi',
                'Obi',
                'Ogbadibo',
                'Oju',
                'Okpokwu',
                'Ohimini',
                'Oturkpo',
                'Tarka',
                'Ukum',
                'Ushongo',
                'Vandeikya'
            ]
        ],
        7 => [
            'name' => 'Bornu',
            'capital' => 'Maiduguri',
            'lga' => [
                'Abadam',
                'Askira/Uba',
                'Bama',
                'Bayo',
                'Biu',
                'Chibok',
                'Damboa',
                'Dikwa',
                'Gubio',
                'Guzamala',
                'Gwoza',
                'Hawul',
                'Jere',
                'Kaga',
                'Kala/Balge',
                'Konduga',
                'Kukawa',
                'Kwaya Kusar',
                'Mafa',
                'Magumeri',
                'Maiduguri',
                'Marte',
                'Mobbar',
                'Monguno',
                'Ngala',
                'Nganzai',
                'Shani'
            ]
        ],
        8 => [
            'name' => 'Cross River',
            'capital' => 'Calabar',
            'lga' => [
                'Akpabuyo',
                'Odukpani',
                'Akamkpa',
                'Biase',
                'Abi',
                'Ikom',
                'Yarkur',
                'Odubra',
                'Boki',
                'Ogoja',
                'Yala',
                'Obanliku',
                'Obudu',
                'Calabar South',
                'Etung',
                'Bekwara',
                'Bakassi',
                'Calabar Municipality'
            ]
        ],
        9 => [
            'name' => 'Delta',
            'capital' => 'Asaba',
            'lga' => [
                'Oshimili',
                'Aniocha',
                'Aniocha South',
                'Ika South',
                'Ika North-East',
                'Ndokwa West',
                'Ndokwa East',
                'Isoko south',
                'Isoko North',
                'Bomadi',
                'Burutu',
                'Ughelli South',
                'Ughelli North',
                'Ethiope West',
                'Ethiope East',
                'Sapele',
                'Okpe',
                'Warri North',
                'Warri South',
                'Uvwie',
                'Udu',
                'Warri Central',
                'Ukwani',
                'Oshimili North',
                'Patani'
            ]
        ],
        10 => [
            'name' => 'Ebonyi',
            'capital' => 'Abakaliki',
            'lga' => [
                'Afikpo South',
                'Afikpo North',
                'Onicha',
                'Ohaozara',
                'Abakaliki',
                'Ishielu',
                'lkwo',
                'Ezza',
                'Ezza South',
                'Ohaukwu',
                'Ebonyi',
                'Ivo'
            ]
        ],
        11 => [
            'name' => 'Edo',
            'capital' => 'Benin City',
            'lga' => [
                'Esan North-East',
                'Esan Central',
                'Esan West',
                'Egor',
                'Ukpoba',
                'Central',
                'Etsako Central',
                'Igueben',
                'Oredo',
                'Ovia SouthWest',
                'Ovia South-East',
                'Orhionwon',
                'Uhunmwonde',
                'Etsako East',
                'Esan South-East'
            ]
        ],
        12 => [
            'name' => 'Ekiti',
            'capital' => 'Ado Ekiti',
            'lga' => [
                'Ado',
                'Ekiti-East',
                'Ekiti-West',
                'Emure/Ise/Orun',
                'Ekiti South-West',
                'Ikare',
                'Irepodun',
                'Ijero',
                'Ido/Osi',
                'Oye',
                'Ikole',
                'Moba',
                'Gbonyin',
                'Efon',
                'Ise/Orun',
                'Ilejemeje'
            ]
        ],
        13 => [
            'name' => 'Enugu',
            'capital' => 'Enugu',
            'lga' => [
                'Enugu South',
                'Igbo-Eze South',
                'Enugu North',
                'Nkanu',
                'Udi Agwu',
                'Oji-River',
                'Ezeagu',
                'IgboEze North',
                'Isi-Uzo',
                'Nsukka',
                'Igbo-Ekiti',
                'Uzo-Uwani',
                'Enugu East',
                'Aninri',
                'Nkanu East',
                'Udenu'
            ]
        ],
        14 => [
            'name' => 'Gombe',
            'capital' => 'Gombe',
            'lga' => [
                'Akko',
                'Balanga',
                'Billiri',
                'Dukku',
                'Kaltungo',
                'Kwami',
                'Shomgom',
                'Funakaye',
                'Gombe',
                'Nafada/Bajoga',
                'Yamaltu/Delta'
            ]
        ],
        15 => [
            'name' => 'Imo',
            'capital' => 'Owerri',
            'lga' => [
                'Aboh-Mbaise',
                'Ahiazu-Mbaise',
                'Ehime-Mbano',
                'Ezinihitte',
                'Ideato North',
                'Ideato South',
                'Ihitte/Uboma',
                'Ikeduru',
                'Isiala Mbano',
                'Isu',
                'Mbaitoli',
                'Mbaitoli',
                'Ngor-Okpala',
                'Njaba',
                'Nwangele',
                'Nkwerre',
                'Obowo',
                'Oguta',
                'Ohaji/Egbema',
                'Okigwe',
                'Orlu',
                'Orsu',
                'Oru East',
                'Oru West',
                'Owerri-Municipal',
                'Owerri North',
                'Owerri West'
            ]
        ],
        16 => [
            'name' => 'Jigawa',
            'capital' => 'Dutse',
            'lga' => [
                'Auyo',
                'Babura',
                'Birni Kudu',
                'Biriniwa',
                'Buji',
                'Dutse',
                'Gagarawa',
                'Garki',
                'Gumel',
                'Guri',
                'Gwaram',
                'Gwiwa',
                'Hadejia',
                'Jahun',
                'Kafin Hausa',
                'Kaugama Kazaure',
                'Kiri Kasamma',
                'Kiyawa',
                'Maigatari',
                'Malam Madori',
                'Miga',
                'Ringim',
                'Roni',
                'Sule-Tankarkar',
                'Taura',
                'Yankwashi'
            ]
        ],
        17 => [
            'name' => 'Kaduna',
            'capital' => 'Kaduna',
            'lga' => [
                'Birni-Gwari',
                'Chikun',
                'Giwa',
                'Igabi',
                'Ikara',
                'jaba',
                'Jema\'a',
                'Kachia',
                'Kaduna North',
                'Kaduna South',
                'Kagarko',
                'Kajuru',
                'Kaura',
                'Kauru',
                'Kubau',
                'Kudan',
                'Lere',
                'Makarfi',
                'Sabon-Gari',
                'Sanga',
                'Soba',
                'Zango-Kataf',
                'Zaria'
            ]
        ],
        18 => [
            'name' => 'Kano',
            'capital' => 'Kano',
            'lga' => [
                'Ajingi',
                'Albasu',
                'Bagwai',
                'Bebeji',
                'Bichi',
                'Bunkure',
                'Dala',
                'Dambatta',
                'Dawakin Kudu',
                'Dawakin Tofa',
                'Doguwa',
                'Fagge',
                'Gabasawa',
                'Garko',
                'Garum',
                'Mallam',
                'Gaya',
                'Gezawa',
                'Gwale',
                'Gwarzo',
                'Kabo',
                'Kano Municipal',
                'Karaye',
                'Kibiya',
                'Kiru',
                'kumbotso',
                'Kunchi',
                'Kura',
                'Madobi',
                'Makoda',
                'Minjibir',
                'Nasarawa',
                'Rano',
                'Rimin Gado',
                'Rogo',
                'Shanono',
                'Sumaila',
                'Takali',
                'Tarauni',
                'Tofa',
                'Tsanyawa',
                'Tudun Wada',
                'Ungogo',
                'Warawa',
                'Wudil'
            ]
        ],
        19 => [
            'name' => 'Katsina',
            'capital' => 'Kastina',
            'lga' => [
                'Bakori',
                'Batagarawa',
                'Batsari',
                'Baure',
                'Bindawa',
                'Charanchi',
                'Dandume',
                'Danja',
                'Dan Musa',
                'Daura',
                'Dutsi',
                'Dutsin-Ma',
                'Faskari',
                'Funtua',
                'Ingawa',
                'Jibia',
                'Kafur',
                'Kaita',
                'Kankara',
                'Kankia',
                'Katsina',
                'Kurfi',
                'Kusada',
                'Mai\'Adua',
                'Malumfashi',
                'Mani',
                'Mashi',
                'Matazuu',
                'Musawa',
                'Rimi',
                'Sabuwa',
                'Safana',
                'Sandamu',
                'Zango'
            ]
        ],
        20 => [
            'name' => 'Kebbi',
            'capital' => 'Birnin Kebbi',
            'lga' => [
                'Aleiro',
                'Arewa-Dandi',
                'Argungu',
                'Augie',
                'Bagudo',
                'Birnin Kebbi',
                'Bunza',
                'Dandi',
                'Fakai',
                'Gwandu',
                'Jega',
                'Kalgo',
                'Koko/Besse',
                'Maiyama',
                'Ngaski',
                'Sakaba',
                'Shanga',
                'Suru',
                'Wasagu/Danko',
                'Yauri',
                'Zuru'
            ]
        ],
        21 => [
            'name' => 'Kogi',
            'capital' => 'Lokoja',
            'lga' => [
                'Adavi',
                'Ajaokuta',
                'Ankpa',
                'Bassa',
                'Dekina',
                'Ibaji',
                'Idah',
                'Igalamela-Odolu',
                'Ijumu',
                'Kabba/Bunu',
                'Kogi',
                'Lokoja',
                'Mopa-Muro',
                'Ofu',
                'Ogori/Mangongo',
                'Okehi',
                'Okene',
                'Olamabolo',
                'Omala',
                'Yagba East',
                'Yagba West'
            ]
        ],
        22 => [
            'name' => 'Kwara',
            'capital' => 'Ilorin',
            'lga' => [
                'Asa',
                'Baruten',
                'Edu',
                'Ekiti',
                'Ifelodun',
                'Ilorin East',
                'Ilorin West',
                'Irepodun',
                'Isin',
                'Kaiama',
                'Moro',
                'Offa',
                'Oke-Ero',
                'Oyun',
                'Pategi'
            ]
        ],
        23 => [
            'name' => 'Lagos',
            'capital' => 'Ikeja',
            'lga' => [
                'Agege',
                'Ajeromi-Ifelodun',
                'Alimosho',
                'Amuwo-Odofin',
                'Apapa',
                'Badagry',
                'Epe',
                'Eti-Osa',
                'Ibeju/Lekki',
                'Ifako-Ijaye',
                'Ikeja',
                'Ikorodu',
                'Kosofe',
                'Lagos Island',
                'Lagos Mainland',
                'Mushin',
                'Ojo',
                'Oshodi-Isolo',
                'Shomolu',
                'Surulere'
            ]
        ],
        24 => [
            'name' => 'Nasarawa',
            'capital' => 'Lafia',
            'lga' => [
                'Akwanga',
                'Awe',
                'Doma',
                'Karu',
                'Keana',
                'Keffi',
                'Kokona',
                'Lafia',
                'Nasarawa',
                'Nasarawa-Eggon',
                'Obi',
                'Toto',
                'Wamba'
            ]
        ],
        25 => [
            'name' => 'Niger',
            'capital' => 'Minna',
            'lga' => [
                'Agaie',
                'Agwara',
                'Bida',
                'Borgu',
                'Bosso',
                'Chanchaga',
                'Edati',
                'Gbako',
                'Gurara',
                'Katcha',
                'Kontagora',
                'Lapai',
                'Lavun',
                'Magama',
                'Mariga',
                'Mashegu',
                'Mokwa',
                'Muya',
                'Pailoro',
                'Rafi',
                'Rijau',
                'Shiroro',
                'Suleja',
                'Tafa',
                'Wushishi'
            ]
        ],
        26 => [
            'name' => 'Ogun',
            'capital' => 'Abeokuta',
            'lga' => [
                'Abeokuta North',
                'Abeokuta South',
                'Ado-Odo/Ota',
                'Egbado North',
                'Egbado South',
                'Ewekoro',
                'Ifo',
                'Ijebu East',
                'Ijebu North',
                'Ijebu North East',
                'Ijebu Ode',
                'Ikenne',
                'Imeko-Afon',
                'Ipokia',
                'Obafemi-Owode',
                'Ogun Waterside',
                'Odeda',
                'Odogbolu',
                'Remo North',
                'Shagamu'
            ]
        ],
        27 => [
            'name' => 'Ondo',
            'capital' => 'Akure',
            'lga' => [
                'Akoko North East',
                'Akoko North West',
                'Akoko South Akure East',
                'Akoko South West',
                'Akure North',
                'Akure South',
                'Ese-Odo',
                'Idanre',
                'Ifedore',
                'Ilaje',
                'Ile-Oluji',
                'Okeigbo',
                'Irele',
                'Odigbo',
                'Okitipupa',
                'Ondo East',
                'Ondo West',
                'Ose',
                'Owo'
            ]
        ],
        28 => [
            'name' => 'Osun',
            'capital' => 'Oshogbo',
            'lga' => [
                'Aiyedade',
                'Aiyedire',
                'Atakumosa East',
                'Atakumosa West',
                'Boluwaduro',
                'Boripe',
                'Ede North',
                'Ede South',
                'Egbedore',
                'Ejigbo',
                'Ife Central',
                'Ife East',
                'Ife North',
                'Ife South',
                'Ifedayo',
                'Ifelodun',
                'Ila',
                'Ilesha East',
                'Ilesha West',
                'Irepodun',
                'Irewole',
                'Isokan',
                'Iwo',
                'Obokun',
                'Odo-Otin',
                'Ola-Oluwa',
                'Olorunda',
                'Oriade',
                'Orolu',
                'Osogbo'
            ]
        ],
        29 => [
            'name' => 'Oyo',
            'capital' => 'Ibadan',
            'lga' => [
                'Afijio',
                'Akinyele',
                'Atiba',
                'Atigbo',
                'Egbeda',
                'Ibadan Central',
                'Ibadan North',
                'Ibadan North West',
                'Ibadan South East',
                'Ibadan South West',
                'Ibarapa Central',
                'Ibarapa East',
                'Ibarapa North',
                'Ido',
                'Irepo',
                'Iseyin',
                'Itesiwaju',
                'Iwajowa',
                'Kajola',
                'Lagelu Ogbomosho North',
                'Ogbmosho South',
                'Ogo Oluwa',
                'Olorunsogo',
                'Oluyole',
                'Ona-Ara',
                'Orelope',
                'Ori Ire',
                'Oyo East',
                'Oyo West',
                'Saki East',
                'Saki West',
                'Surulere'
            ]
        ],
        30 => [
            'name' => 'Plateau',
            'capital' => 'Jos',
            'lga' => [
                'Barikin Ladi',
                'Bassa',
                'Bokkos',
                'Jos East',
                'Jos North',
                'Jos South',
                'Kanam',
                'Kanke',
                'Langtang North',
                'Langtang South',
                'Mangu',
                'Mikang',
                'Pankshin',
                'Qua\'an Pan',
                'Riyom',
                'Shendam',
                'Wase'
            ]
        ],
        31 => [
            'name' => 'Rivers',
            'capital' => 'Port Harcourt',
            'lga' => [
                'Abua/Odual',
                'Ahoada East',
                'Ahoada West',
                'Akuku Toru',
                'Andoni',
                'Asari-Toru',
                'Bonny',
                'Degema',
                'Emohua',
                'Eleme',
                'Etche',
                'Gokana',
                'Ikwerre',
                'Khana',
                'Obia/Akpor',
                'Ogba/Egbema/Ndoni',
                'Ogu/Bolo',
                'Okrika',
                'Omumma',
                'Opobo/Nkoro',
                'Oyigbo',
                'Port-Harcourt',
                'Tai'
            ]
        ],
        32 => [
            'name' => 'Sokoto',
            'capital' => 'Sokoto',
            'lga' => [
                'Binji',
                'Bodinga',
                'Dange-shnsi',
                'Gada',
                'Goronyo',
                'Gudu',
                'Gawabawa',
                'Illela',
                'Isa',
                'Kware',
                'kebbe',
                'Rabah',
                'Sabon birni',
                'Shagari',
                'Silame',
                'Sokoto North',
                'Sokoto South',
                'Tambuwal',
                'Tqngaza',
                'Tureta',
                'Wamako',
                'Wurno',
                'Yabo'
            ]
        ],
        33 => [
            'name' => 'Taraba',
            'capital' => 'Jalingo',
            'lga' => [
                'Ardo-kola',
                'Bali',
                'Donga',
                'Gashaka',
                'Cassol',
                'Ibi',
                'Jalingo',
                'Karin-Lamido',
                'Kurmi',
                'Lau',
                'Sardauna',
                'Takum',
                'Ussa',
                'Wukari',
                'Yorro',
                'Zing'
            ]
        ],
        34 => [
            'name' => 'Yobe',
            'capital' => 'Damaturu',
            'lga' => [
                'Bade',
                'Bursari',
                'Damaturu',
                'Fika',
                'Fune',
                'Geidam',
                'Gujba',
                'Gulani',
                'Jakusko',
                'Karasuwa',
                'Karawa',
                'Machina',
                'Nangere',
                'Nguru Potiskum',
                'Tarmua',
                'Yunusari',
                'Yusufari'
            ]
        ],
        35 => [
            'name' => 'Zamfara',
            'capital' => 'Gusau',
            'lga' => [
                'Anka',
                'Bakura',
                'Birnin Magaji',
                'Bukkuyum',
                'Bungudu',
                'Gummi',
                'Gusau',
                'Kaura',
                'Namoda',
                'Maradun',
                'Maru',
                'Shinkafi',
                'Talata Mafara',
                'Tsafe',
                'Zurmi'
            ]
        ],
        36 => [
            'name' => 'Abuja',
            'capital' => '',
            'lga' => [
                'Gwagwalada',
                'Kuje',
                'Abaji',
                'Abuja Municipal',
                'Bwari',
                'Kwali'
            ]
        ]
    ],

    'categories' => [
        'books',
        'articles',
        'journals',
        'papers',
        'conferences',
        'researches',
        'reports',
        'festchrisfts',
        'monographs',
    ],

    'users' => [
        'super_admin' => [
            'first_name' => 'Super',
            'last_name' => 'Bookstore',
            'email' => 'superadmin@bookstore.com',
            'phone' => '+2340812345678',
            'is_verified' => 1,
            'email_verified_at' => Carbon\Carbon::now(),
            'password' => \Illuminate\Support\Facades\Hash::make('password'),
            'role' => 'super_admin'
        ],
        'admin' => [
            'first_name' => 'Admin',
            'last_name' => 'Bookstore',
            'email' => 'admin@bookstore.com',
            'phone' => '+2347812345678',
            'is_verified' => 1,
            'email_verified_at' => Carbon\Carbon::now(),
            'password' => \Illuminate\Support\Facades\Hash::make('password'),
            'role' => 'admin'
        ],
        'user' => [
            'first_name' => 'User',
            'last_name' => 'Bookstore',
            'email' => 'user@bookstore.com',
            'phone' => '+2349812345678',
            'is_verified' => 1,
            'email_verified_at' => Carbon\Carbon::now(),
            'password' => \Illuminate\Support\Facades\Hash::make('password'),
            'role' => 'user'
        ],
        'reviewer' => [
            'first_name' => 'Reviewer',
            'last_name' => 'Bookstore',
            'email' => 'reviewer@bookstore.com',
            'phone' => '+2349112345678',
            'is_verified' => 1,
            'email_verified_at' => Carbon\Carbon::now(),
            'password' => \Illuminate\Support\Facades\Hash::make('password'),
            'role' => 'reviewer'
        ],
    ]

];

